name: Doxygen

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate documentation
        run: doxygen Doxyfile
