name: CMake

on:
  push:
    branches: [ "main" ]
    paths: &monitored-paths
      - "github/workflows/cmake.yml"
      - "CMakeLists.txt"
      - "sources/**"
      - "headers/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths: *monitored-paths

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_type: Release
          - os: ubuntu-latest
            build_type: Release
          - os: macos-latest
            build_type: Release
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Configure CMake
        run: >
          cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -G
          "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 

      - name: Build
        run: >
          cmake --build ${{ github.workspace }}/build --config ${{
          matrix.build_type }}

      - name: Test
        working-directory: ${{ github.workspace }}/build/tests
        run: >
          ctest --build-config ${{ matrix.build_type }}
